### PR TITLE
Update For Most Recent Version of Kaminari

### PR DESCRIPTION
**Pull request by bewitchingme**
I could not run the test suite to verify this change (the test suite dies when I try to run it) but this solved every issue I had with use of this gem.

### CODE REVIEW

**Comment by apotonick** [comment]
Is that for the newest version of Cells or Kaminari?

**Comment by bewitchingme** [comment]
Ah, apologies, it's for the most recent version of Kaminari.  The #paginate method was in the Kaminari::ActionViewExtension namespace, in the most recent version it has been moved into Kaminari::Helpers::HelperMethods.

**Comment by apotonick** [comment]
Cool, please also bump up the kaminari requirement in the `gemspec` file. :heart:

**Comment by bewitchingme** [comment]
I've updated the gemspec; once merged, would you leave a message with me once you've pushed the updated gem to rubygems?

**Comment by george-carlin** [comment]
Thanks, but this has now been fixed by https://github.com/apotonick/kaminari-cells/pull/8

I think that now that this gem is (I think?) compatible with Kaminari 1.0.0, it's worthy of a major version bump. How about releasing `master` as 1.0.0? @apotonick?

**Comment by george-carlin** [comment]
Okay, I just released `kaminari-cells 1.0.0`, which is compatible (or at least it should be!) with kaminari 1+. For Kaminari <1, use `kaminari-cells 0.1.0` (which I also just released.)

**Pull request closed without merging**
