### PR TITLE
Change included Kaminari helper module for Kaminari 1.0.0 compatibility

### PR DESCRIPTION
**Pull request by tjjjwxzq**
Fix breakage due to changes in file structure in Kaminari 1.0.0 by including the appropriate helper module.

### CODE REVIEW

**Comment by tjjjwxzq** [comment]
hmmm rack and activesupport require ruby >= 2.2.2?

**Comment by tjjjwxzq** [comment]
sorry @apotonick, this is actually my first ever open source PR (and I'm a relative newb to programming in general), so I'm not quite sure how I should be going about it :sweat_smile:

**Comment by apotonick** [comment]
Hey, all good and great commit, it's just that Kaminari is on a very low level of my priorities ATM. :wink:

**Comment by SweeD** [comment]
@apotonick
Is there anything we could do to get this into master, soon? 
Would be awesome to be able to use kaminari in cells. 😊

**Comment by apotonick** [comment]
Für Säufer tu ich fast alles!

@georgemillo ??? :stuck_out_tongue_winking_eye:

**Comment by george-carlin** [comment]
Okay, I just released `kaminari-cells 1.0.0`, which is compatible (or at least it should be!) with kaminari 1+. For Kaminari <1, use `kaminari-cells 0.1.0` (which I also just released.)

**Comment by george-carlin** [comment]
PS thanks @tjjjwxzq for fixing this! Sorry for the delay.

**Comment by tjjjwxzq** [comment]
@georgemillo ah awesome!

**Comment by apotonick** [comment]
> this is actually my first ever open source PR

@tjjjwxzq It might be your first PR ever but your presentation at RedDot didn't look like it's your first talk. Amazing job! :sparkles: I learned a lot about meta-meta-meta classes (and I *had* a feeling I never really understood the meta-meta layer)... :rofl:

**Comment by tjjjwxzq** [comment]
Thank you @apotonick! :smile_cat: Thanks for Trailblazer too and a chance for me to do my first OSS contrib :joy: (I'm afraid meta-meta-meta classes don't help much here...)

**Comment by apotonick** [comment]
Well, let's put it that way, it's good to know meta-classes but I honestly had no idea that for every class a meta class (or meta-meta-meta-meta) is generated! :female_detective:

**Pull request merged**
